init task-1
SPuDI-zzz/JSLabsQPD pull request #1
Opened 2023-12-22 15:31 UTC by SPuDI-zzz

Add MyDifference, MyIsEqual and MySortedUniq

2023-12-23 13:23 UTC, Dtroonn requested changes

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +        return value !== value && other !== other;
не понимаю смысл этой строчки она всегда возвращает false. По логике должно же быть value === other. 
Да и в принципе зачем это условие, если по сути в isDeepEqual это все обработано

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return value.toString() === other.toString();
Ты сравниваешь функцию по названию, но могут прилететь функции с одинаковыми названиями, но они будут разными. Надо сравнивать по ссылке. Функция - объект по - сути.  Просто в тестах такой кейс не прописан походу.

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return MyIsEqual(setToArray(value), setToArray(other));
Все сводится к массивам через Array.from и setToArray  - не нужен

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return MyIsEqual(mapToArray(value), mapToArray(other));
Все сводится к объектам через статич. метод Object.fromEntries => mapToArray не нужен

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/Difference.js
> +function MyDifference(arrA, arrB) {
1) Ф-ия difference из lodash принимает бесконечн. множество аргументов через запятую. В твоей же реализации, такого не предусмотрено 

2) Нет никакого смысла использовать внутри MyIsEqual т.к  в оригинальной функции lodash если передать два одинаковых объекта в разных массивах, но с разными ссылками, то в результате этот объект останется в массиве. 

3) Даже если убрать MyIsEqual, то сложность твоего алгоритма останется O(n^2) , подумать над тем как ускорить.

2023-12-23 13:23 UTC, Dtroonn commented on Тема№1 с тестами/Task1/SortedUniq.js
> +    return resultArray;
Можно сделать  return Array.from(new Set(array)) и сложность алгоритма останется такой же. 
MyIsEqual нет смысла использовать т.к в ф-ии из lodash глубого сравнения не предусмотрено

2023-12-24 00:34 UTC, SPuDI-zzz commented on Тема№1 с тестами/Task1/IsEqual.js
> +        return value !== value && other !== other;
возвращает true, если NaN !== NaN https://learn.javascript.ru/number#proverka-isfinite-i-isnan

2023-12-24 00:45 UTC, SPuDI-zzz commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return MyIsEqual(mapToArray(value), mapToArray(other));
вот почему я так сделал
const map1 = new Map();
map1.set(5, 5);
map1.set("some text", "text");
var obj = { a: 1, b: 2 };
map1.set(obj, obj);
map1.set({ a: 1, b: 2 }, 123);
![image](https://github.com/SPuDI-zzz/JSLabsQPD/assets/81990805/030e4134-9489-4ac6-a6db-9b5de9e2ab40)

2023-12-24 00:59 UTC, SPuDI-zzz commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return value.toString() === other.toString();
по ссылке они сравниваются в самом начале MyIsEqual. Вроде в самом lodash, если там функции не равны по ссылке, то возвращать false, поэтому можно написать 
case 'Function': return false;

2023-12-24 02:12 UTC, SPuDI-zzz commented on Тема№1 с тестами/Task1/SortedUniq.js
> +    return resultArray;
Про глубокое сравнение согласен, но там точно не Set. Вот почему
![image](https://github.com/SPuDI-zzz/JSLabsQPD/assets/81990805/d486f46a-1045-44f1-a796-66923226510f)

2023-12-24 17:46 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return value.toString() === other.toString();
> по ссылке они сравниваются в самом начале MyIsEqual. Вроде в самом lodash, если там функции не равны по ссылке, то возвращать false, поэтому можно написать case 'Function': return false;


в чем смысл сравнивать в начале ф-ии MyIsEqual , если у тебя это все сравнивается в deepEqual. 

> по ссылке они сравниваются в самом начале MyIsEqual. Вроде в самом lodash, если там функции не равны по ссылке, то возвращать false, поэтому можно написать case 'Function': return false;

Какой смысл сравнивать в начале MyIsEqual, если у тебя происходят сравнения в deepEqual ? Только теперь у тебя deepEqual возвращает для ф-ий всегда false, что выглядит странно. Я бы убрал первую проверку в MyIsEqual и добавил бы сравнение ф-ий по ссылке в deepEqual

2023-12-24 17:47 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +        return value !== value && other !== other;
> возвращает true, если NaN !== NaN https://learn.javascript.ru/number#proverka-isfinite-i-isnan

Понял, тяжело читать. Лучше использовать isNaN

2023-12-24 17:53 UTC, Dtroonn commented on Тема№1 с тестами/Task1/IsEqual.js
> +            return MyIsEqual(mapToArray(value), mapToArray(other));
> вот почему я так сделал const map1 = new Map(); map1.set(5, 5); map1.set("some text", "text"); var obj = { a: 1, b: 2 }; map1.set(obj, obj); map1.set({ a: 1, b: 2 }, 123); ![image](https://private-user-images.githubusercontent.com/81990805/292650092-030e4134-9489-4ac6-a6db-9b5de9e2ab40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDAxMTQsIm5iZiI6MTcwMzQzOTgxNCwicGF0aCI6Ii84MTk5MDgwNS8yOTI2NTAwOTItMDMwZTQxMzQtOTQ4OS00YWM2LWE2ZGItOWI1ZGU5ZTJhYjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE3NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzZlNjJlNzExZDg1ZWIxYzk0OTZmYTVkNTQwODAwMjcwZTJmZDI3NDdlZjIzYmRjYjA3OGRlYzc2MTQyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4RkBkY7aRq8Tcgleo5Deg6KWKs4so9IyGXMZzhUGgY)

Cправедливо, вижу что заюзал Array.from вместо

2023-12-24 17:55 UTC, Dtroonn commented on Тема№1 с тестами/Task1/SortedUniq.js
> +    return resultArray;
> Про глубокое сравнение согласен, но там точно не Set. Вот почему ![image](https://private-user-images.githubusercontent.com/81990805/292651913-d486f46a-1045-44f1-a796-66923226510f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDAxMTQsIm5iZiI6MTcwMzQzOTgxNCwicGF0aCI6Ii84MTk5MDgwNS8yOTI2NTE5MTMtZDQ4NmY0NmEtMTA0NS00NGYxLWE3OTYtNjY5MjMyMjY1MTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE3NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYTFmZjJjZjQ3MGE5MWVjMTBhNWFiZWNlNzRmYmU4MTViZDAyYjFkMDc5ZjY4ZTI3YzhkNTZkY2M5MWU5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5R7RuyK1inzppqAvZCJmE6NPZ-aLfFLqMUvlzcX6HAU)

Да, там не Set т.к оптимизировано под сортированные массивы, я это написал т.к Set не проигрывает по сложности алгоритма твоему решению. но выглядит компактнее

2023-12-24 18:05 UTC, Dtroonn approved these changes

2023-12-24 21:38 UTC, merged